### ISSUE TITLE
Deadlock in `HttpServerHostContext.Dispose()`

### ISSUE THREAD

**Issue by Infiziert90** [sisk-http/core#10]
**Which Sisk package is this bug related?**
- Sisk.Core

**Describe the bug**
The application doesn't finish its dispose, it gets stuck and prevents a clean shutdown off any surrounding libraries

The sample code below runs fine, it would display a webpage if a router was linked, it also writes "Starting dispose" to the console, but after `HostContext.HttpServer.Stop();` the deadlock happens in `HostContext.Dispose();`, the next console line is never written

**To Reproduce**
```cs
class Program
{
    static void Main(string[] args)
    {
        var core = new ServerCore();
        core.Start();
        Thread.Sleep(10000);

        Console.WriteLine("Starting dispose");
        core.Dispose();
    }

}

public class ServerCore : IDisposable
{
    private readonly HttpServerHostContext HostContext;

    public ServerCore()
    {
        HostContext = HttpServer.CreateBuilder().UseListeningPort(5523).Build();
        HostContext.ServerConfiguration.AccessLogsStream = new LogStream("logs/access.log");
        HostContext.ServerConfiguration.ErrorsLogsStream = new LogStream("logs/error.log");

    }

    public void Start()
    {
         HostContext.Start(preventHault: false);
    }

    public void Dispose()
    {
        HostContext.HttpServer.Stop();
        HostContext.Dispose();
        Console.WriteLine("Disposing done...");
    }
}
```

**Expected behavior**
It should succesful dispose and leave the function scope

**Desktop (please complete the following information):**
- Windows 10 22H2
- .NET 8
- 1.0.0 from NuGet

**Comment by Infiziert90** [comment]
A screenshot if the stack that it loops consistently through

![image](https://github.com/user-attachments/assets/7dd5ed1a-a76d-4213-ac0e-6a573ab08c9e)

**Comment by CypherPotato** [comment]
Hello, thank you for your submission.

I was able to reproduce the issue. From what I've investigated, it seems to be related to the LogStreams. More precisely, the `LogStream.Flush()` method, which is called in `LogStream.Dispose`. It blocks and waits for the log consumer to signal that there are no more logs to be written, and it is a blocking task.

The problem was that `LogStream.Flush()` was being called before `channel.Writer.Complete()`, which indicates that no more logs would be written to that LogStream, causing an infinite wait. In https://github.com/sisk-http/core/commit/5d9a0dc41012a757154ed935bbb46a4a5f953baf, I reversed the method call and ensured that the end event of the consumer is triggered at its conclusion.

Running it again, after the change, the server can now correctly finalize with `Dispose()`. I would appreciate it if you could also test on your end to confirm whether the issue has been resolved. If everything checks out, I'll schedule a hotfix for an upcoming update.

**Comment by Infiziert90** [comment]
Gave it a quick test with my sample code above and it seems to dispose correctly now 👍
