### ISSUE TITLE
How i can use swagger?

### ISSUE THREAD

**Issue by ketronix-dev** [sisk-http/core#13]
How i can add swagger to my project with sisk?

**Comment by CypherPotato** [comment]
I have been thinking about this in recent days, but I haven't reached a conclusion. The short answer is that Sisk does not have a swagger generation tool because it cannot assume what your request expects or what response will be sent. All of this is verified at the moment a request arrives at its route and when the server delivers the response.

Sisk can know the path and method that a route is receiving, as well as its path parameters, but nothing beyond that. To develop a swagger extension, Sisk would need to somehow know what type of body is expected in the request and what type of response will be sent.

Nothing prevents you from defining your own swagger using [Router.GetDefinedRoutes()](https://docs.sisk-framework.org/api/Sisk.Core.Routing.Router.GetDefinedRoutes) or manually.

If you have any ideas or suggestions, feel free to create an extension for that. Maybe I can help you with that.
