### ISSUE TITLE
Running Sisk with https protocol

### ISSUE THREAD

**Issue by nicholas-peterson** [sisk-http/core#2]
Is there a minimal example of starting Sisk using https protocol? I tried just changing a working configuration from:
`new ListeningPort(false, "localhost", 5000)`
to
`new ListeningPort(true, "localhost", 5000)`
And the server starts and doesn't report an error, but I cannot access it. I've tried a few other variants such as 
`new (ListeningPort("https://localhost:5001")` but see the same result. Not sure if I'm missing something obvious?

**Comment by CypherPotato** [comment]
This is not related to Sisk framework itself and this issue will depend on the operating system where Sisk is running since the implementation of the HttpListener, which is the core for processing HTTP requests/responses, changes from one system to another.

On **Windows**, you need your user account to have the permissions to listen to a virtual host (when not using "localhost" or not running as elevated mode) and you need to associate an SSL certificate on that host. This is not done in Sisk directly, but by IIS. I can provide a tutorial soon in the documentation on how to enable self-signed SSL on Windows, but either way, you will need to have IIS installed on the machine. You can get started with it [here](https://learn.microsoft.com/en-us/iis/manage/configuring-security/how-to-set-up-ssl-on-iis).

For other systems, such as **Unix-based**, the HTTPS protocol implementation is different, made directly in the code, but does not support SSL. Connection to these systems is made using HTTP/1.1. In this case, it is recommended to use a reverse proxy to provide traffic between the internet and your Sisk application. I've used nginx before and Cloudflared, and both worked well.

**Comment by nicholas-peterson** [comment]
First, thanks for this great explanation and for Sisk! I'd love some documentation or a quickstart involving IIS as a reverse proxy to Sisk + Basic Auth and SSL. I get that writing that kind of stuff is time consuming, so no worries if it isn't on the radar. I think this would be a really common requirement of users though, who want to host a Sisk HTTP service, but have to secure it. Basic auth may be fine, but it pretty much requires SSL from a security perspective.

**Comment by CypherPotato** [comment]
Published to [Sisk docs](https://sisk.project-principium.dev/read?q=/contents/docs/deploying.md) at https://github.com/sisk-http/docs/commit/f185e34641c6a924259486d2a379536235a712b9
