### ISSUE TITLE
MAUI REST API + static file server

### ISSUE THREAD

**Issue by milten89** [sisk-http/core#9]
Hi,

We like to use Sisk in our MAUI project. Did You know about any issues when using Sisk in MAUI on Andorid or iOS platform?

Short description of our current project status:
- frontend is written React and must be hosted locally (preferable by Sisk)
- backend is written in ASP.NET Core, and we need to replace it with other HTTP server (preferable by Sisk)
- on other platforms we use docker, and it works like a charm

ASP.NET Core officially don't have support on MAUI, and we don't want to use hacks to compile it (https://github.com/JamesNK/aspnetcore-maui), because we can encounter some problems in the future, that can be too hard or impossible to fix.

Right now we are looking for some HTTP server, on with we can easily migrate our controllers and this library is looking promising.

Best regards

**Comment by CypherPotato** [comment]
Hello, thank you for your issue.

Sisk works entirely on top of HttpListener as their HTTP socket provider. As far as I know, HttpListener implementation is compatible with Android and iOS. I have only been able to test on Windows and Linux so far, I have not been able to test on other platforms.

Sisk must be compatible with anything where HttpListener is supported, since Sisk is an interface built on top of it and uses no dependencies other than .NET itself. If you are going to compile for Native AOT, there are few limitations, such as not being able to use the router's AutoScan (if you trim the assembly where your routes are), but I don't see how it wouldn't be compatible with the full CLR runtime on it.

One way to get a known whether the environment will support Sisk is to validate whether [HttpListener.IsSupported](https://learn.microsoft.com/pt-br/dotnet/api/system.net.httplistener.issupported) is true.

If you want to try out some preliminary tests with Sisk and MAUI, I would be happy to see the results and help your development if you have any questions or problems.
